src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Table(name: 'book')]
#[ORM\Entity(repositoryClass: BookRepository::class)]
class Book
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(name: 'id', type: 'integer')]
    private ?int $id = null;

    #[ORM\Column(name: 'title', type: 'string', length: 255)]
    private ?string $title = null;

    #[ORM\Column(name: 'author', type: 'string', length: 255)]
    private ?string $author = null;

    #[ORM\Column(name: 'isbn', type: 'string', length: 255)]
    private ?string $isbn = null;

    #[ORM\Column(name: 'page', type: 'integer')]
    private ?int $page = null;

    #[ORM\Column(name: 'is_borrowed', type: 'boolean', options: ['default' => false])]
    private ?bool $isBorrowed = false;

    /**
     * @var Collection<int, BorrowRecord>
     */
    #[ORM\OneToMany(targetEntity: BorrowRecord::class, mappedBy: 'book_id')]
    private Collection $borrowRecords;

    public function __construct()
    {
        $this->borrowRecords = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): static
    {
        $this->author = $author;

        return $this;
    }

    public function getIsbn(): ?string
    {
        return $this->isbn;
    }

    public function setIsbn(string $isbn): static
    {
        $this->isbn = $isbn;

        return $this;
    }

    public function getPage(): ?int
    {
        return $this->page;
    }

    public function setPage(int $page): static
    {
        $this->page = $page;

        return $this;
    }

    public function isBorrowed(): ?bool
    {
        return $this->isBorrowed;
    }

    public function setBorrowed(bool $isBorrowed): static
    {
        $this->isBorrowed = $isBorrowed;

        return $this;
    }

    /**
     * @return Collection<int, BorrowRecord>
     */
    public function getBorrowRecords(): Collection
    {
        return $this->borrowRecords;
    }

    public function addBorrowRecord(BorrowRecord $borrowRecord): static
    {
        if (!$this->borrowRecords->contains($borrowRecord)) {
            $this->borrowRecords->add($borrowRecord);
            $borrowRecord->setBookId($this);
        }

        return $this;
    }

    public function removeBorrowRecord(BorrowRecord $borrowRecord): static
    {
        if ($this->borrowRecords->removeElement($borrowRecord)) {
            // set the owning side to null (unless already changed)
            if ($borrowRecord->getBookId() === $this) {
                $borrowRecord->setBookId(null);
            }
        }

        return $this;
    }
}

src/Form/BookType.php
<?php

namespace App\Form;

use App\Entity\Book;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BookType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('author')
            ->add('isbn')
            ->add('page')
            ->add('save', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Book::class,
        ]);
    }
}

src/Controller/BookController.php
<?php

namespace App\Controller;

use App\Entity\Book;
use App\Form\BookType;
use App\Repository\BookRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class BookController extends AbstractController
{
    #[Route('/books', name: 'book_list', methods: ['GET'])]
    public function listBooks(ManagerRegistry $registry): Response
    {
        $bookRepository = new BookRepository($registry);
        $list = $bookRepository->listBook();
        return $this->render('book/list.html.twig', ['books' => $list]);
    }

    #[Route('/book/add', name: 'book_add', methods: ['GET', 'POST'])]
    public function add(Request $request, ManagerRegistry $registry): Response
    {
        $book = new Book();
        $form = $this->createForm(BookType::class, $book);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $bookRepository = new BookRepository($registry);
            $bookRepository->createBook($book);
            return $this->redirectToRoute('book_list');
        }

        return $this->render('book/add.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}

templates/book/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Book Create{% endblock %}

{% block body %}
    {{ form(form) }}

    <a href="{{ path('book_list') }}">Back to list</a>
{% endblock %}

templates/book/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello BookController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code>/Users/sanemugur/Desktop/Document Sanem/wms-service/src/Controller/BookController.php</code></li>
        <li>Your template at <code>/Users/sanemugur/Desktop/Document Sanem/wms-service/templates/book/index.html.twig</code></li>
    </ul>
</div>
{% endblock %}

templates/book/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Book List{% endblock %}

{% block body %}
    <h1>Book List</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Author</th>
                <th>ISBN</th>
                <th>Page</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for book in books %}
                <tr>
                    <td>{{ book.id }}</td>
                    <td>{{ book.title }}</td>
                    <td>{{ book.author }}</td>
                    <td>{{ book.isbn }}</td>
                    <td>{{ book.page }}</td>
                    <td>
                        {% if book.borrowed is empty %}
                            <a href="{{ path('borrow_book', {'recordId': book.id}) }}">Borrow</a>
                        {% else %}
                            <a href="{{ path('return_book', {'recordId': book.id}) }}">Return</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('book_add') }}">Create new</a>
{% endblock %}